---
ospf:
 rid: 2.2.2.2
 default_originate: false
 networks:
   - prefix: "10.1.2.0/30"
     area: "0"
   - prefix: "10.2.3.0/30"
     area: "0"
   - prefix: "10.2.4.0/30"
     area: "0"
   - prefix: "2.2.2.2/32"
     area: "0"

bgp:
  asn: "2"
  rid: "2.2.2.2"
  neighbors:
    - neighbor: "10.1.2.1"
      peer_asn: "1"
    - neighbor: "10.2.3.2"
      peer_asn: "3"
    - neighbor: "10.2.4.2"
      peer_asn: "4"

vlans:
  interfaces:
    - interface: "Et6"
      mode: access
      vlan: "5"
    - interface: "Et5"
      mode: access
      vlan: "10"
    - interface: "Et2"
      mode: trunk
  vlan:
    - number: "5"
      name: "FIVE"
      svi: "192.168.5.2 255.255.255.0"
    - number: "10"
      name: "TEN"
      svi: "192.168.10.2 255.255.255.0"
      
# bgp_style: bgp

# ntp: "8.8.8.8"

# BGP:
#   ASN: "65002"
#   peers: 
#     - neighbor: 10.199.199.11
#       peer_asn: "65001"

#     - neighbor: 10.199.199.10
#       peer_asn: "65010"

#     - neighbor: 192.168.77.1
#       peer_asn: "771"

# ntp:
#   servers:
#     - 1.1.1.1
#     - 2.2.2.2
#     - 5.5.5.5

# syslog:
#   hosts:
#     - ip: 11.11.11.11

#     - ip: 22.22.22.22
#       port: 1234

#     - ip: 44.44.44.44
#       port: 4567

#     - ip: 55.55.55.55

#     - ip: 77.77.77.77
#       port: 7777