---
syslog: 
  hosts:
    - ip: 11.11.11.1
    - ip: 2.2.2.2
      port: 1234
    - ip: 3.3.3.3
    - ip: 44.44.44.4
      port: 5678
    - ip: 55.55.55.55
    - ip: 77.77.77.77
      port: 7891

ospf_configure:
  Cisco-IOS-XE-native:router:
    Cisco-IOS-XE-ospf:router-ospf:
      ospf:
        process-id:
        - id: 1
          network:
          - area: 0
            ip: 10.1.1.1
            wildcard: 0.0.0.0
          - area: 0
            ip: 10.1.2.1
            wildcard: 0.0.0.0
          - area: 0
            ip: 10.1.3.1
            wildcard: 0.0.0.0
        - id: 19
          router-id: 33.44.88.22

ansible_user: "developer"
ansible_password: "C1sco12345"


acl_configure:
  Cisco-IOS-XE-native:access-list:
    Cisco-IOS-XE-acl:extended:
    - access-list-seq-rule:
      - ace-rule:
          action: permit
          dst-any:
          -
          dst-eq: 22
          ipv4-address: 10.123.23.0
          mask: 0.0.0.255
          protocol: tcp
        sequence: '10'
      name: ACL_VTY-IN

