---

- name: "Playbook1: Testing Genie"
  hosts: switch
  connection: network_cli

  tasks:
    - name: "Task 1 - send a show command"
      arista.eos.eos_command:
        commands: "show version"
      register: show_version_output

    - name: "Task 2 - Parse show command"
      set_fact: 
        parsed_data: >-
          {{ show_version_output.stdout[0] | clay584.genie.parse_genie(command='show version', os='eos') }}

    - name: "Task 3- print show command"
      ansible.builtin.debug:
        msg: "This device has been up for {{ parsed_data.version.uptime }}"
