---

- name: "REGISTER PLAYBOOK"
  hosts: switch
  gather_facts: false
  connection: network_cli

  tasks:
   - name: "Push NTP config"
     arista.eos.eos_config:
       src: "ntp.j2"
     register: ntp_result

   - name: "Print result"
     debug:
       msg:  "{{ ntp_result.commands }}"