---

- name: "Vyos Playbook"
  hosts: vyos
  connection: network_cli

  tasks:
    - name: "Push some banner configuration to Vyos"
      vyos.vyos.vyos_banner:
        banner: pre-login
        text: "CBT NUGGETS BANNER for vyos"
        state: present
      register: vyos_output
      when: "ansible_network_os == 'vyos.vyos.vyos'"
    
    - name: "Print vyos VLAN Config"
      debug:
        msg: "{{ vyos_output.commands | to_nice_json }}"
      when: "ansible_network_os == 'vyos.vyos.vyos'"