---

- name: "Vyos Playbook"
  hosts: vyos
  connection: network_cli

  tasks:
    - name: "Push some banner configuration to Vyos"
      vyos.vyos.vyos_banner:
        banner: pre-login
        text: "Willies BANNER for VyOS"
        state: present