---
- name: "TEST SETUP MODULE PLAYBOOK"
  hosts: localhost

  tasks:
    - name: "Collect facts aobut local host"
      ansible.builtin.setup:
        gather_subset:
          - "min"
      register: output

    - name: "Print facts from local host min"
      debug:
        # msg: "{{ output.ansible_facts.ansible_date_time.iso8601 | to_nice_json }}"
        msg: "{{ output.ansible_facts.ansible_date_time.date | to_nice_json }}"