---
- name: "TEST SETUP MODULE PLAYBOOK"
  hosts: localhost

  tasks:
    - name: "Collect facts aobut local host"
      ansible.builtin.setup:
        filter:
          - "ansible_date_time"
      register: output

    - name: "Task2: Recording Variable as a fact"
      set_fact:
        datetime: "{{ ansible_date_time.date }}"

    - name: "Task3 - Creating directories with file module"
      file:
        path:  "Backups/{{ datetime }}"
        state: directory
      run_once: true

   