---

- name: "Playbook to test NAPALM ANSIBLE"
  hosts: cisco, arista
  connection: network_cli

  tasks:
    - name: "Retrieve devices facts via NAPALM"
      napalm_get_facts:
        hostname: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
        filter: ["facts"]
      
      register: result

    - name: "Print Result"
      debug:
        msg: "{{ result.ansible_facts.napalm_facts | to_yaml(indent=8, width=1337) }}"
        # msg: "{{ result.ansible_facts.napalm_facts | to_nice_json  }}"
        