---

- name: "Playbook to test NAPALM ANSIBLE"
  hosts: cisco, arista
  connection: network_cli

  tasks:
    - name: "Retrieve devices facts via NAPALM"
      napalm_get_facts:
        hostname: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
        # filter: ["interfaces_ip"]
        # filter: ["interfaces_counters"]
        # filter: ["mac_address_table"]
        # You can chain your napalm fiters using a comma
        filter: ["vlans"]
      
      register: result

    - name: "Print Result"
      debug:
        # msg: "{{ result.ansible_facts.napalm_mac_address_table[0].mac }}"
        # msg: "{{ result.ansible_facts.napalm_mac_address_table }}"
        msg: "{{ result.ansible_facts.napalm_vlans | to_nice_json }}"
      # when: "ansible_network_os == 'arista.eos.eos'"