---

- name: "NAPALM PLAYBOOK TO VALIDATE DEVICES"
  hosts: arista, cisco
  connection: network_cli

  tasks:
    - name: " Task1 - use NAPALM VALIDATE "
      napalm_validate:
        hostname: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
        validation_file: "{{ inventory_hostname}}-ip.yml"
      register: result
      ignore_errors: yes

    - name: "Task1 - print the result"
      debug:
        msg: "{{ result | to_nice_json }}"