---

bgp_style: bgp

BGP:
  ASN: "65001"
  peers: 
    - neighbor: 10.199.199.12
      peer_asn: "65002"

    - neighbor: 10.199.199.10
      peer_asn: "65010"

    - neighbor: 192.168.77.1
      peer_asn: "771"

ntp:
  servers:
    - 1.1.1.1
    - 2.2.2.2
    - 5.5.5.5