---

ntp: "8.8.8.8"

BGP:
  ASN: "65002"
  peers: 
    - neighbor: 10.199.199.11
      peer_asn: "65001"

    - neighbor: 10.199.199.10
      peer_asn: "65010"

    - neighbor: 192.168.77.1
      peer_asn: "771"