---
bgp_style: bgp

BGP:
  ASN: "65010"
  peers: 
    - neighbor: 10.199.199.11
      peer_asn: "65001"

    - neighbor: 10.199.199.12
      peer_asn: "65002"

    - neighbor: 192.168.77.1
      peer_asn: "771"

ntp:
  servers:
    - 1.1.1.1
    - 2.2.2.2
    - 5.5.5.5
    - 7.7.7.7
    - 8.8.8.8
    - 9.9.9.9
    - 10.10.10.10

syslog:
  hosts:
    - ip: 10.10.10.10

    - ip: 20.20.20.20
      port: 1234

    - ip: 40.40.40.40
      port: 4567